#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Deploys the full sidereal protocol to Stellar testnet and writes the resulting
# contract addresses to app/.env.local for the frontend.
#
# No private keys are hardcoded. The deployer identity is created with
# `stellar keys generate` and stored by the CLI; only its public address is ever
# echoed. Re-run safe: pass DEPLOY_IDENTITY to reuse an existing funded key.
#
# Requirements: stellar-cli (https://stellar.org/developers), Rust with the
# wasm32v1-none target, run from the repo root.

set -euo pipefail

REPO="${REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$REPO"

NETWORK="${NETWORK:-testnet}"
IDENTITY="${DEPLOY_IDENTITY:-sidereal-deployer}"
WASM_DIR="target/wasm32v1-none/release"
ENV_OUT="${ENV_OUT:-app/.env.local}"

# AMM curve parameters (mirror the verified defaults in the AMM test suite).
WAD="1000000000000000000"
SCALAR_ROOT="${SCALAR_ROOT:-2000000000000000000}"     # 2.0 * WAD
INITIAL_ANCHOR="${INITIAL_ANCHOR:-1050000000000000000}" # 1.05 * WAD
FEE_BPS="${FEE_BPS:-10}"                                # 0.10%
TWAP_WINDOW="${TWAP_WINDOW:-1800}"                      # 30 minutes

# Maturity: default to ~90 days out (one quarter), overridable. Unix seconds.
MATURITY="${MATURITY:-$(( $(date -u +%s) + 90 * 86400 ))}"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v stellar >/dev/null 2>&1 || die "stellar-cli not found. Install: cargo install --locked stellar-cli"

log "Building contracts to wasm ($WASM_DIR)"
cargo build --release --target wasm32v1-none \
  -p sidereal-sy-wrapper -p sidereal-pt-token -p sidereal-yt-token \
  -p sidereal-tokenizer -p sidereal-amm

# --- deployer identity -------------------------------------------------------
if ! stellar keys address "$IDENTITY" >/dev/null 2>&1; then
  log "Generating and funding deployer identity '$IDENTITY' on $NETWORK"
  stellar keys generate --global "$IDENTITY" --network "$NETWORK" --fund
fi
ADMIN="$(stellar keys address "$IDENTITY")"
log "Deployer address: $ADMIN"

deploy() {
  # deploy <wasm-name> -> echoes contract id
  stellar contract deploy \
    --wasm "$WASM_DIR/$1.wasm" \
    --source "$IDENTITY" --network "$NETWORK" 2>/dev/null
}

invoke() {
  # invoke <contract-id> <fn> [args...]
  local id="$1"; shift
  stellar contract invoke --id "$id" --source "$IDENTITY" --network "$NETWORK" -- "$@" >/dev/null
}

# --- underlying asset --------------------------------------------------------
# The SY wrapper stores an underlying address. For a testnet demo we deploy the
# Stellar Asset Contract for a test USDC issued by the deployer unless an
# existing contract id is supplied via UNDERLYING.
if [[ -n "${UNDERLYING:-}" ]]; then
  UNDERLYING_ID="$UNDERLYING"
  log "Using provided underlying: $UNDERLYING_ID"
else
  log "Deploying test-USDC Stellar Asset Contract"
  UNDERLYING_ID="$(stellar contract asset deploy --asset "USDC:$ADMIN" \
    --source "$IDENTITY" --network "$NETWORK" 2>/dev/null)"
fi
log "Underlying (USDC): $UNDERLYING_ID"

# --- deploy contracts (addresses known before init resolves the cycle) -------
log "Deploying SY wrapper";  SY="$(deploy sidereal_sy_wrapper)";  log "  SY=$SY"
log "Deploying PT token";    PT="$(deploy sidereal_pt_token)";    log "  PT=$PT"
log "Deploying YT token";    YT="$(deploy sidereal_yt_token)";    log "  YT=$YT"
log "Deploying tokenizer";   TK="$(deploy sidereal_tokenizer)";   log "  TK=$TK"
log "Deploying AMM";         AMM="$(deploy sidereal_amm)";        log "  AMM=$AMM"

# --- initialize in dependency order ------------------------------------------
log "Initializing SY wrapper"
invoke "$SY" initialize --admin "$ADMIN" --underlying "$UNDERLYING_ID"

log "Initializing PT token"
invoke "$PT" initialize --admin "$ADMIN" --tokenizer "$TK" --sy_token "$SY" --maturity "$MATURITY"

log "Initializing YT token"
invoke "$YT" initialize --admin "$ADMIN" --tokenizer "$TK" --sy_token "$SY" --maturity "$MATURITY"

log "Initializing tokenizer"
invoke "$TK" initialize --admin "$ADMIN" --sy_token "$SY" --pt_token "$PT" --yt_token "$YT" --maturity "$MATURITY"

log "Initializing AMM"
invoke "$AMM" initialize \
  --admin "$ADMIN" --pt_token "$PT" --sy_token "$SY" --tokenizer "$TK" \
  --maturity "$MATURITY" --scalar_root "$SCALAR_ROOT" --initial_anchor "$INITIAL_ANCHOR" \
  --fee_bps "$FEE_BPS" --twap_window "$TWAP_WINDOW"

# --- write frontend env ------------------------------------------------------
log "Writing $ENV_OUT"
cat > "$ENV_OUT" <<EOF
# Generated by scripts/deploy-testnet.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Public values only.
NEXT_PUBLIC_SOROBAN_RPC_URL="https://soroban-testnet.stellar.org"
NEXT_PUBLIC_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
NEXT_PUBLIC_MARKET_ID="blend-usdc-q3"
NEXT_PUBLIC_TOKEN_DECIMALS="7"
NEXT_PUBLIC_SY_ADDRESS="$SY"
NEXT_PUBLIC_PT_ADDRESS="$PT"
NEXT_PUBLIC_YT_ADDRESS="$YT"
NEXT_PUBLIC_TOKENIZER_ADDRESS="$TK"
NEXT_PUBLIC_MARKET_ADDRESS="$AMM"
EOF

log "Done. Maturity=$MATURITY ($(date -u -r "$MATURITY" +%Y-%m-%d 2>/dev/null || echo "$MATURITY"))"
log "Frontend is wired. Start it with: pnpm --filter @sidereal/app dev"
