#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Resumable testnet deployment for the full Sidereal protocol.
#
# This script is intentionally stricter than the legacy deploy helper:
# - it refuses tracked dirty source by default, so a manifest can point to one
#   committed source revision;
# - it persists every deployed address before moving to the next step;
# - it reuses the persisted underlying SAC address on reruns;
# - it writes both app/.env.local and deployments/testnet.toml after success.
#
# No private keys are written. The deployment state and final manifest contain
# public contract addresses, public deployer address, source commit, parameters,
# and bytecode hashes.

set -euo pipefail

REPO="${REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
cd "$REPO"

NETWORK="${NETWORK:-testnet}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"
IDENTITY="${DEPLOY_IDENTITY:-sidereal-deployer}"
WASM_DIR="${WASM_DIR:-target/wasm32v1-none/release}"
DEPLOYMENTS_DIR="${DEPLOYMENTS_DIR:-deployments}"
STATE_FILE="${STATE_FILE:-$DEPLOYMENTS_DIR/$NETWORK.state.env}"
MANIFEST_OUT="${MANIFEST_OUT:-$DEPLOYMENTS_DIR/$NETWORK.toml}"
ENV_OUT="${ENV_OUT:-app/.env.local}"

WAD="1000000000000000000"
SCALAR_ROOT="${SCALAR_ROOT:-2000000000000000000}"
INITIAL_ANCHOR="${INITIAL_ANCHOR:-1050000000000000000}"
FEE_BPS="${FEE_BPS:-10}"
TWAP_WINDOW="${TWAP_WINDOW:-1800}"
MATURITY="${MATURITY:-$(( $(date -u +%s) + 90 * 86400 ))}"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "$1 not found"
}

tracked_dirty() {
  git status --porcelain --untracked-files=no
}

quote_env() {
  printf '%q' "$1"
}

save_state() {
  mkdir -p "$DEPLOYMENTS_DIR"
  local tmp
  tmp="$(mktemp "$STATE_FILE.tmp.XXXXXX")"
  {
    printf 'DEPLOY_STARTED_AT=%s\n' "$(quote_env "${DEPLOY_STARTED_AT:-}")"
    printf 'SOURCE_COMMIT=%s\n' "$(quote_env "${SOURCE_COMMIT:-}")"
    printf 'NETWORK=%s\n' "$(quote_env "$NETWORK")"
    printf 'NETWORK_PASSPHRASE=%s\n' "$(quote_env "$NETWORK_PASSPHRASE")"
    printf 'IDENTITY=%s\n' "$(quote_env "$IDENTITY")"
    printf 'DEPLOYER_ADDRESS=%s\n' "$(quote_env "${DEPLOYER_ADDRESS:-}")"
    printf 'MATURITY=%s\n' "$(quote_env "$MATURITY")"
    printf 'SCALAR_ROOT=%s\n' "$(quote_env "$SCALAR_ROOT")"
    printf 'INITIAL_ANCHOR=%s\n' "$(quote_env "$INITIAL_ANCHOR")"
    printf 'FEE_BPS=%s\n' "$(quote_env "$FEE_BPS")"
    printf 'TWAP_WINDOW=%s\n' "$(quote_env "$TWAP_WINDOW")"
    printf 'UNDERLYING_ID=%s\n' "$(quote_env "${UNDERLYING_ID:-}")"
    printf 'SY=%s\n' "$(quote_env "${SY:-}")"
    printf 'PT=%s\n' "$(quote_env "${PT:-}")"
    printf 'YT=%s\n' "$(quote_env "${YT:-}")"
    printf 'TK=%s\n' "$(quote_env "${TK:-}")"
    printf 'AMM=%s\n' "$(quote_env "${AMM:-}")"
    printf 'INIT_SY=%s\n' "$(quote_env "${INIT_SY:-0}")"
    printf 'INIT_PT=%s\n' "$(quote_env "${INIT_PT:-0}")"
    printf 'INIT_YT=%s\n' "$(quote_env "${INIT_YT:-0}")"
    printf 'INIT_TK=%s\n' "$(quote_env "${INIT_TK:-0}")"
    printf 'INIT_AMM=%s\n' "$(quote_env "${INIT_AMM:-0}")"
  } > "$tmp"
  mv "$tmp" "$STATE_FILE"
}

load_state() {
  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    log "Loaded deploy state from $STATE_FILE"
  fi
}

deploy_wasm_once() {
  local var_name="$1"
  local wasm_name="$2"
  local current="${!var_name:-}"

  if [[ -n "$current" ]]; then
    log "Reusing $var_name=$current"
    return
  fi

  log "Deploying $wasm_name"
  local deployed
  deployed="$(stellar contract deploy \
    --wasm "$WASM_DIR/$wasm_name.wasm" \
    --source "$IDENTITY" \
    --network "$NETWORK" 2>/dev/null)"
  printf -v "$var_name" '%s' "$deployed"
  save_state
  log "  $var_name=$deployed"
}

invoke_once() {
  local marker="$1"
  local contract_id="$2"
  shift 2

  if [[ "${!marker:-0}" == "1" ]]; then
    log "Skipping already completed init marker $marker"
    return
  fi

  stellar contract invoke \
    --id "$contract_id" \
    --source "$IDENTITY" \
    --network "$NETWORK" \
    -- "$@" >/dev/null
  printf -v "$marker" '%s' "1"
  save_state
}

wasm_hash() {
  stellar contract info hash --wasm "$1"
}

onchain_hash() {
  stellar contract info hash --id "$1" --network "$NETWORK"
}

write_frontend_env() {
  log "Writing $ENV_OUT"
  cat > "$ENV_OUT" <<EOF
# Generated by scripts/deploy-testnet-resilient.sh on $DEPLOY_FINISHED_AT. Public values only.
# Source commit: $SOURCE_COMMIT
NEXT_PUBLIC_SOROBAN_RPC_URL="https://soroban-testnet.stellar.org"
NEXT_PUBLIC_NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"
NEXT_PUBLIC_SIMULATION_SOURCE_ADDRESS="$DEPLOYER_ADDRESS"
NEXT_PUBLIC_MARKET_ID="blend-usdc-q3"
NEXT_PUBLIC_TOKEN_DECIMALS="7"
NEXT_PUBLIC_SY_ADDRESS="$SY"
NEXT_PUBLIC_PT_ADDRESS="$PT"
NEXT_PUBLIC_YT_ADDRESS="$YT"
NEXT_PUBLIC_TOKENIZER_ADDRESS="$TK"
NEXT_PUBLIC_MARKET_ADDRESS="$AMM"
EOF
}

write_manifest() {
  log "Writing $MANIFEST_OUT"
  mkdir -p "$DEPLOYMENTS_DIR"
  cat > "$MANIFEST_OUT" <<EOF
# Generated by scripts/deploy-testnet-resilient.sh.
# Public deployment metadata only. Do not add private keys.

network = "$NETWORK"
network_passphrase = "$NETWORK_PASSPHRASE"
source_commit = "$SOURCE_COMMIT"
deployer_identity = "$IDENTITY"
deployer_public_key = "$DEPLOYER_ADDRESS"
deployed_at = "$DEPLOY_FINISHED_AT"
maturity = $MATURITY
token_decimals = 7

[curve]
scalar_root = "$SCALAR_ROOT"
initial_anchor = "$INITIAL_ANCHOR"
fee_bps = $FEE_BPS
twap_window = $TWAP_WINDOW

[contracts]
underlying = "$UNDERLYING_ID"
sy_wrapper = "$SY"
pt_token = "$PT"
yt_token = "$YT"
tokenizer = "$TK"
amm = "$AMM"

[wasm_hashes]
sy_wrapper = "$SY_WASM_HASH"
pt_token = "$PT_WASM_HASH"
yt_token = "$YT_WASM_HASH"
tokenizer = "$TK_WASM_HASH"
amm = "$AMM_WASM_HASH"

[onchain_hashes]
sy_wrapper = "$SY_CHAIN_HASH"
pt_token = "$PT_CHAIN_HASH"
yt_token = "$YT_CHAIN_HASH"
tokenizer = "$TK_CHAIN_HASH"
amm = "$AMM_CHAIN_HASH"

[frontend]
env_file = "$ENV_OUT"
simulation_source = "$DEPLOYER_ADDRESS"
market_id = "blend-usdc-q3"
EOF
}

require_cmd git
require_cmd cargo
require_cmd stellar

if [[ "${SKIP_WASM_FLOAT_CHECK:-0}" != "1" ]]; then
  require_cmd wasm-objdump
fi

dirty="$(tracked_dirty)"
if [[ -n "$dirty" && "${ALLOW_DIRTY:-0}" != "1" ]]; then
  printf '%s\n' "$dirty" >&2
  die "tracked source is dirty. Commit first or set ALLOW_DIRTY=1 for a non-reproducible dry run"
fi

CURRENT_SOURCE_COMMIT="$(git rev-parse HEAD)"
load_state

if [[ -n "${SOURCE_COMMIT:-}" && "$SOURCE_COMMIT" != "$CURRENT_SOURCE_COMMIT" ]]; then
  die "state file was created from $SOURCE_COMMIT, but current source is $CURRENT_SOURCE_COMMIT"
fi

SOURCE_COMMIT="$CURRENT_SOURCE_COMMIT"
DEPLOY_STARTED_AT="${DEPLOY_STARTED_AT:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
save_state

log "Building contracts to wasm from $SOURCE_COMMIT"
cargo build --release --target wasm32v1-none --locked \
  -p sidereal-sy-wrapper -p sidereal-pt-token -p sidereal-yt-token \
  -p sidereal-tokenizer -p sidereal-amm

if [[ "${SKIP_WASM_FLOAT_CHECK:-0}" != "1" ]]; then
  bash scripts/check-wasm-floats.sh \
    "$WASM_DIR/sidereal_sy_wrapper.wasm" \
    "$WASM_DIR/sidereal_pt_token.wasm" \
    "$WASM_DIR/sidereal_yt_token.wasm" \
    "$WASM_DIR/sidereal_tokenizer.wasm" \
    "$WASM_DIR/sidereal_amm.wasm"
fi

SY_WASM_HASH="$(wasm_hash "$WASM_DIR/sidereal_sy_wrapper.wasm")"
PT_WASM_HASH="$(wasm_hash "$WASM_DIR/sidereal_pt_token.wasm")"
YT_WASM_HASH="$(wasm_hash "$WASM_DIR/sidereal_yt_token.wasm")"
TK_WASM_HASH="$(wasm_hash "$WASM_DIR/sidereal_tokenizer.wasm")"
AMM_WASM_HASH="$(wasm_hash "$WASM_DIR/sidereal_amm.wasm")"

if ! stellar keys address "$IDENTITY" >/dev/null 2>&1; then
  log "Generating and funding deployer identity '$IDENTITY' on $NETWORK"
  stellar keys generate --global "$IDENTITY" --network "$NETWORK" --fund
fi
DEPLOYER_ADDRESS="$(stellar keys address "$IDENTITY")"
save_state
log "Deployer address: $DEPLOYER_ADDRESS"

if [[ -n "${UNDERLYING:-}" ]]; then
  UNDERLYING_ID="$UNDERLYING"
  save_state
  log "Using provided underlying: $UNDERLYING_ID"
elif [[ -n "${UNDERLYING_ID:-}" ]]; then
  log "Reusing underlying from state: $UNDERLYING_ID"
else
  log "Deploying test-USDC Stellar Asset Contract"
  UNDERLYING_ID="$(stellar contract asset deploy \
    --asset "USDC:$DEPLOYER_ADDRESS" \
    --source "$IDENTITY" \
    --network "$NETWORK" 2>/dev/null)"
  save_state
  log "Underlying (USDC): $UNDERLYING_ID"
fi

deploy_wasm_once SY sidereal_sy_wrapper
deploy_wasm_once PT sidereal_pt_token
deploy_wasm_once YT sidereal_yt_token
deploy_wasm_once TK sidereal_tokenizer
deploy_wasm_once AMM sidereal_amm

log "Initializing SY wrapper"
invoke_once INIT_SY "$SY" initialize --admin "$DEPLOYER_ADDRESS" --underlying "$UNDERLYING_ID"

log "Initializing PT token"
invoke_once INIT_PT "$PT" initialize --admin "$DEPLOYER_ADDRESS" --tokenizer "$TK" --sy_token "$SY" --maturity "$MATURITY"

log "Initializing YT token"
invoke_once INIT_YT "$YT" initialize --admin "$DEPLOYER_ADDRESS" --tokenizer "$TK" --sy_token "$SY" --maturity "$MATURITY"

log "Initializing tokenizer"
invoke_once INIT_TK "$TK" initialize --admin "$DEPLOYER_ADDRESS" --sy_token "$SY" --pt_token "$PT" --yt_token "$YT" --maturity "$MATURITY"

log "Initializing AMM"
invoke_once INIT_AMM "$AMM" initialize \
  --admin "$DEPLOYER_ADDRESS" \
  --pt_token "$PT" \
  --sy_token "$SY" \
  --yt_token "$YT" \
  --tokenizer "$TK" \
  --maturity "$MATURITY" \
  --scalar_root "$SCALAR_ROOT" \
  --initial_anchor "$INITIAL_ANCHOR" \
  --fee_bps "$FEE_BPS" \
  --twap_window "$TWAP_WINDOW"

SY_CHAIN_HASH="$(onchain_hash "$SY")"
PT_CHAIN_HASH="$(onchain_hash "$PT")"
YT_CHAIN_HASH="$(onchain_hash "$YT")"
TK_CHAIN_HASH="$(onchain_hash "$TK")"
AMM_CHAIN_HASH="$(onchain_hash "$AMM")"

[[ "$SY_WASM_HASH" == "$SY_CHAIN_HASH" ]] || die "SY Wasm hash mismatch"
[[ "$PT_WASM_HASH" == "$PT_CHAIN_HASH" ]] || die "PT Wasm hash mismatch"
[[ "$YT_WASM_HASH" == "$YT_CHAIN_HASH" ]] || die "YT Wasm hash mismatch"
[[ "$TK_WASM_HASH" == "$TK_CHAIN_HASH" ]] || die "tokenizer Wasm hash mismatch"
[[ "$AMM_WASM_HASH" == "$AMM_CHAIN_HASH" ]] || die "AMM Wasm hash mismatch"

DEPLOY_FINISHED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
write_frontend_env
write_manifest

log "Deployment complete"
log "Manifest: $MANIFEST_OUT"
log "Frontend env: $ENV_OUT"
warn "Review and commit $MANIFEST_OUT after verifying the deployment. Do not commit $ENV_OUT or $STATE_FILE."
